// AUTO-GENERATED by tools/generate-icons.mjs — do not edit by hand.
// Source: src/assets/icons/*.svg. Regenerate with `npm run icons`.

export interface ImsIconDefinition {
    /** Human-readable name, used when an instance opts into `label="true"`. */
    readonly label: string;
    /** Complete `<svg>` markup, verbatim from the source file. */
    readonly source: string;
}

export const IMS_ICONS = {
    'add': {
        label: 'Add',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Add</title>
  <circle class="tint" transform="translate(2 2)" cx="16" cy="16" r="12" fill="var(--icon-tint, #BFC2F4)"></circle>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="16" r="12"></circle>
    <path d="M16 10.4v11.2M10.4 16h11.2"></path>
  </g>
</svg>`
    },
    'autocomplete': {
        label: 'Autocomplete',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Autocomplete</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <circle cx="13.4" cy="13.4" r="9.4"></circle>
    <path d="M18.9 21.5 23.9 26.5a1.9 1.9 0 0 0 2.7-2.7L21.5 18.9Z"></path>
    <path d="M24 4 25.1 6.9 28 8 25.1 9.1 24 12 22.9 9.1 20 8 22.9 6.9Z"></path>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="13.4" cy="13.4" r="9.4"></circle>
    <path d="M18.9 21.5 23.9 26.5a1.9 1.9 0 0 0 2.7-2.7L21.5 18.9"></path>
    <path d="M24 4 25.1 6.9 28 8 25.1 9.1 24 12 22.9 9.1 20 8 22.9 6.9Z"></path>
  </g>
</svg>`
    },
    'clear': {
        label: 'Clear',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Clear</title>
  <circle class="tint" transform="translate(2 2)" cx="16" cy="16" r="12" fill="var(--icon-tint, #BFC2F4)"></circle>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="16" r="12"></circle>
    <path d="M11.8 11.8 20.2 20.2M20.2 11.8 11.8 20.2"></path>
  </g>
</svg>`
    },
    'danger': {
        label: 'Danger',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Danger</title>
  <circle class="tint" transform="translate(2 2)" cx="16" cy="16" r="12" fill="var(--icon-tint, #BFC2F4)"></circle>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="16" r="12"></circle>
    <path d="M16 10.4v7.2"></path>
    <path d="M16 21.4h.01"></path>
  </g>
</svg>`
    },
    'edit': {
        label: 'Edit',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Edit</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <path d="M5.6 26.4 10.6 24.8 24.4 11a2.4 2.4 0 0 0-3.4-3.4L7.2 21.4Z"></path>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <path d="M5.6 26.4 10.6 24.8 24.4 11a2.4 2.4 0 0 0-3.4-3.4L7.2 21.4Z"></path>
    <path d="M5.6 26.4 8.9 23.2"></path>
    <path d="M10.6 24.8 7.2 21.4"></path>
    <path d="M20.8 14.6 17.4 11.2"></path>
  </g>
</svg>`
    },
    'expand': {
        label: 'Expand',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Expand</title>
  <circle class="tint" transform="translate(2 2)" cx="16" cy="16" r="12" fill="var(--icon-tint, #BFC2F4)"></circle>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="16" r="12"></circle>
    <path d="M11.2 14.2 16 19 20.8 14.2"></path>
  </g>
</svg>`
    },
    'filter': {
        label: 'Filter',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Filter</title>
  <path class="tint" transform="translate(2 2)" d="M4.6 6.4h22.8l-8.8 9.8v9.4l-5.2-2.6v-6.8Z" fill="var(--icon-tint, #BFC2F4)"></path>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <path d="M4.6 6.4h22.8l-8.8 9.8v9.4l-5.2-2.6v-6.8Z"></path>
    <path d="M13.4 16.2h5.2"></path>
  </g>
</svg>`
    },
    'floppy-disk': {
        label: 'Floppy disk',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Floppy disk</title>
  <path class="tint" transform="translate(2 2)" d="M6 4h16.4L28 9.6V26a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z" fill="var(--icon-tint, #BFC2F4)"></path>
  <path d="M9.4 19.2h13.2V28H9.4zM10 4h9.6v7.6h-9.6z" fill="var(--icon-surface, #fff)"></path>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <path d="M6 4h16.4L28 9.6V26a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"></path>
    <path d="M11.2 4v8h9.6V4"></path>
    <path d="M17.6 6v4"></path>
    <path d="M9.4 28v-8.8h13.2V28"></path>
    <path d="M12.2 22.4h7.6M12.2 25.2h4.4"></path>
  </g>
</svg>`
    },
    'info': {
        label: 'Info',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Info</title>
  <circle class="tint" transform="translate(2 2)" cx="16" cy="16" r="12" fill="var(--icon-tint, #BFC2F4)"></circle>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="16" r="12"></circle>
    <g transform="rotate(8 16 17.5)"><path d="M11.6 15.6c1-2.6 5-3.6 4.4-.8l-1.3 5.5c-.35 2 2.6 2.1 4.3-.3"></path></g>
  </g>
  <path d="M16.9 9.8h.01" fill="none" stroke="var(--icon-contour, #000570)" stroke-width="2.2" stroke-linecap="round"></path>
</svg>`
    },
    'list': {
        label: 'List',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>List</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <rect x="4" y="5.6" width="5.6" height="5.6" rx="1.4"></rect>
    <rect x="4" y="13.2" width="5.6" height="5.6" rx="1.4"></rect>
    <rect x="4" y="20.8" width="5.6" height="5.6" rx="1.4"></rect>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <rect x="4" y="5.6" width="5.6" height="5.6" rx="1.4"></rect>
    <rect x="4" y="13.2" width="5.6" height="5.6" rx="1.4"></rect>
    <rect x="4" y="20.8" width="5.6" height="5.6" rx="1.4"></rect>
    <path d="M5.6 8.4l1.4 1.4 2.4-2.6"></path>
    <path d="M13.6 6.8H28M13.6 10H23"></path>
    <path d="M13.6 14.4H28M13.6 17.6H23"></path>
    <path d="M13.6 22H28M13.6 25.2H23"></path>
  </g>
</svg>`
    },
    'multi-select': {
        label: 'Multi-select',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Multi-select</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <rect x="4" y="5.6" width="9.6" height="9.6" rx="2"></rect>
    <rect x="4" y="17.6" width="9.6" height="9.6" rx="2"></rect>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <rect x="4" y="5.6" width="9.6" height="9.6" rx="2"></rect>
    <rect x="4" y="17.6" width="9.6" height="9.6" rx="2"></rect>
    <path d="M7.2 10.4 8.8 12 10.4 8.8"></path>
    <path d="M7.2 22.4 8.8 24 10.4 20.8"></path>
    <path d="M17.2 10.4H28M17.2 22.4H28"></path>
  </g>
</svg>`
    },
    'remove': {
        label: 'Remove',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Remove</title>
  <circle class="tint" transform="translate(2 2)" cx="16" cy="16" r="12" fill="var(--icon-tint, #BFC2F4)"></circle>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="16" r="12"></circle>
    <path d="M10.4 16h11.2"></path>
  </g>
</svg>`
    },
    'search': {
        label: 'Search',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Search</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <circle cx="13.8" cy="13.8" r="9.8"></circle>
    <path d="M19.3 21.9 24.3 26.9a1.9 1.9 0 0 0 2.7-2.7L21.9 19.3Z"></path>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="13.8" cy="13.8" r="9.8"></circle>
    <path d="M19.3 21.9 24.3 26.9a1.9 1.9 0 0 0 2.7-2.7L21.9 19.3"></path>
  </g>
</svg>`
    },
    'user': {
        label: 'User',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>User</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <circle cx="16" cy="10.6" r="5.8"></circle>
    <path d="M4.6 28c0-5.8 5.1-9.4 11.4-9.4S27.4 22.2 27.4 28Z"></path>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="16" cy="10.6" r="5.8"></circle>
    <path d="M4.6 28c0-5.8 5.1-9.4 11.4-9.4S27.4 22.2 27.4 28"></path>
    <path d="M12.6 19.4l3.4 3.2 3.4-3.2M16 22.6V28"></path>
  </g>
</svg>`
    },
    'warning': {
        label: 'Warning',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Warning</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <path d="M14.7 5.4 4.5 23.2a1.5 1.5 0 0 0 1.3 2.2h20.4a1.5 1.5 0 0 0 1.3-2.2L17.3 5.4a1.5 1.5 0 0 0-2.6 0Z"></path>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <path d="M14.7 5.4 4.5 23.2a1.5 1.5 0 0 0 1.3 2.2h20.4a1.5 1.5 0 0 0 1.3-2.2L17.3 5.4a1.5 1.5 0 0 0-2.6 0Z"></path>
    <path d="M16 12.4v5.6"></path>
    <path d="M16 21.4h.01"></path>
  </g>
</svg>`
    },
    'zoom-in': {
        label: 'Zoom in',
        source: `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" fill="none" focusable="false" aria-hidden="true">
  <title>Zoom in</title>
  <g class="tint" transform="translate(2 2)" fill="var(--icon-tint, #BFC2F4)">
    <circle cx="13.8" cy="13.8" r="9.8"></circle>
    <path d="M19.3 21.9 24.3 26.9a1.9 1.9 0 0 0 2.7-2.7L21.9 19.3Z"></path>
  </g>
  <g fill="none" stroke="var(--icon-contour, #000570)" stroke-width="var(--icon-stroke-width, 1.5)" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="13.8" cy="13.8" r="9.8"></circle>
    <path d="M13.8 9.4v8.8M9.4 13.8h8.8"></path>
    <path d="M19.3 21.9 24.3 26.9a1.9 1.9 0 0 0 2.7-2.7L21.9 19.3"></path>
  </g>
</svg>`
    }
} as const satisfies Record<string, ImsIconDefinition>;

/** Every icon available to `<ims-icon>`. A typo here is a compile error. */
export type ImsIconName = keyof typeof IMS_ICONS;

export const IMS_ICON_NAMES = Object.keys(IMS_ICONS) as readonly ImsIconName[];
